### ISSUE TITLE
Error using Jupyter Hub

### ISSUE THREAD

**Issue by fabiofumarola** [italia/daf#216]
Steps to recreate the bug:

1. create a user
2. login to the data portal private
3. open the datascience
4. it opens jupyter hub with a button with text `start my server`
5. click on it
6. go `500 internal server error`

```
[E 2018-01-23 10:38:19.205 JupyterHub gen:914] Exception in Future &lt;tornado.concurrent.Future object at 0x7fbb51b08358&gt; after timeout
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.5/site-packages/tornado/gen.py", line 910, in error_callback
        future.result()
      File "/opt/conda/lib/python3.5/site-packages/jupyterhub/handlers/base.py", line 444, in finish_user_spawn
        yield spawn_future
      File "/opt/conda/lib/python3.5/site-packages/jupyterhub/user.py", line 476, in spawn
        raise e
      File "/opt/conda/lib/python3.5/site-packages/jupyterhub/user.py", line 450, in spawn
        resp = yield server.wait_up(http=True, timeout=spawner.http_timeout)
      File "/opt/conda/lib/python3.5/site-packages/jupyterhub/utils.py", line 180, in wait_for_http_server
        timeout=timeout
      File "/opt/conda/lib/python3.5/site-packages/jupyterhub/utils.py", line 135, in exponential_backoff
        raise TimeoutError(fail_message)
    TimeoutError: Server at http://127.0.0.1:39616/user/fabiofumarola/ didn't respond in 30 seconds
    
[E 2018-01-23 10:38:19.205 JupyterHub gen:914] Exception in Future &lt;tornado.concurrent.Future object at 0x7fbb51b08358&gt; after timeout
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.5/site-packages/tornado/gen.py", line 910, in error_callback
        future.result()
      File "/opt/conda/lib/python3.5/site-packages/jupyterhub/handlers/base.py", line 444, in finish_user_spawn
        yield spawn_future
      File "/opt/conda/lib/python3.5/site-packages/jupyterhub/user.py", line 476, in spawn
        raise e
      File "/opt/conda/lib/python3.5/site-packages/jupyterhub/user.py", line 450, in spawn
        resp = yield server.wait_up(http=True, timeout=spawner.http_timeout)
      File "/opt/conda/lib/python3.5/site-packages/jupyterhub/utils.py", line 180, in wait_for_http_server
        timeout=timeout
      File "/opt/conda/lib/python3.5/site-packages/jupyterhub/utils.py", line 135, in exponential_backoff
        raise TimeoutError(fail_message)
    TimeoutError: Server at http://127.0.0.1:39616/user/fabiofumarola/ didn't respond in 30 seconds
```

**Comment by giux78** [comment]
The problem seems to be related to old users. For new users jupyterhub works properly. Before close the issue we have to migrate at least daf users.
